# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 344ae45aee0df0afa5255a7e1c9ca8eb0be8e9fad2e21cbc42647e3ff080a4e86b0d3e360bced09f3b161c5cb2b84c0bedd59e6cef7fbea00510500936569f59

test:
  secret_key_base: 1723a9c2d447c2d67f420f3adba3a36b666342a1f10bcbeb5fae97d355ae4d573e2d1e80142c2a0fd11f27c874f8c17438cb65efb569e4d0b7fbe688a28cbd43

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
